package pwsafe

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestReadDBWithoutUUID(t *testing.T) {
	// Create a DB with a known UUID
	db := NewV3("TestDB", "password")
	originalUUID := db.Header.UUID

	// Write it to a buffer
	var buf bytes.Buffer
	err := db.Encrypt(&buf)
	assert.Nil(t, err)

	// Read it back
	readDB := NewV3("", "password")
	_, err = readDB.Decrypt(&buf, "password")
	assert.Nil(t, err)
	assert.Equal(t, originalUUID, readDB.Header.UUID)

	// Now, let's manually construct a DB that is missing the UUID field in the header.
	// This is hard to do without mocking the file content.
	// Alternatively, we can use the fact that simple.dat has no UUID (as discovered).

	// Load simple.dat
	simpleDB, err := OpenPWSafeFile("./test_dbs/simple.dat", "password")
	assert.Nil(t, err)

	// Verify it has a UUID (generated by Decrypt)
	assert.NotEqual(t, [16]byte{}, simpleDB.Header.UUID)

	// Load it again
	simpleDB2, err := OpenPWSafeFile("./test_dbs/simple.dat", "password")
	assert.Nil(t, err)

	// Verify it has a DIFFERENT UUID
	assert.NotEqual(t, simpleDB.Header.UUID, simpleDB2.Header.UUID)
}
